language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/leave_days_test

node_js:
  - "8.9.4"

before_script:
  - psql -c 'create database leave_days_test;' -U postgres
  - psql -U postgres -d leave_days_test -a -f leave-days.sql
  - psql -U postgres -d leave_days_test -a -f insert.sql

addons:
  ? apt
  packages:
    - postgresql-server-dev-9.2
